src/main/java/poolc/poolc/domain/Member.java
=> Feat: MemberDomain Create

src/main/java/poolc/poolc/domain/Board.java, src/main/java/poolc/poolc/domain/Comment.java, src/main/java/poolc/poolc/domain/Post.java
=> Feat. PostDomain Create

src/main/java/poolc/poolc/domain/Book.java, src/main/java/poolc/poolc/enums/BookStatus.java
Close #7 
<br/>
- enum이 필요해서 enum까지 추가하였습니다
<br/><br/>
=> Book domain create

src/main/java/poolc/poolc/domain/Member.java, src/main/java/poolc/poolc/domain/Project.java, src/main/java/poolc/poolc/domain/ProjectMember.java
Close #9
<br/>
- 중간 테이블에 원래 id라는 pk가 없었는데 composite pk 사용시 문제가 있어서 원래 하던대로 id를 만들어서 사용
- 멤버domain도 수정
<br/><br/>
=> Feat : Project Domain Added

src/main/java/poolc/poolc/domain/Activity.java, src/main/java/poolc/poolc/domain/ActivityMember.java, src/main/java/poolc/poolc/domain/ActivityTag.java, src/main/java/poolc/poolc/domain/Attendance.java, src/main/java/poolc/poolc/domain/Session.java, src/main/java/poolc/poolc/domain/Tag.java
Close #6
<br/>
cascade에 관련해서 testcase 코드를 작성 후 문제가 확인되면 추가로 고치겠습니다.
<br/><br/>
=> Feat. ActivityDomain Create

src/main/java/poolc/poolc/domain/Member.java
=> Member domain update

src/main/resources/application.yml
=> Fix: change spring.datasource.url and add show_sql option

src/main/java/poolc/poolc/repository/BookRepository.java
Close #24 
- [o] 신규 기능 추가
<br/>
- 특이 사항 1
- 특이 사항 2
<br/><br/>
=> Feat : BookRepository Create

src/main/java/poolc/poolc/repository/ProjectRepository.java
Close #26 
<br/>
- 단순한 프로젝트 조회용과 멤버들을 전부 조회하는 기능 두개 다 넣었습니다
<br/><br/>
=> Feat : Project Repository added

src/main/java/poolc/poolc/Repository/MemberRepository.java, src/main/java/poolc/poolc/domain/Member.java, src/test/java/poolc/poolc/Repository/MemberRepositoryTest.java
Close #18 
<br/>
- Testcode 추가했습니다.
<br/><br/>
=> Feat. MemberRepository Create

src/main/java/poolc/poolc/domain/ProjectMember.java
=> Fix: ProjectMember not null constraint add

src/main/java/poolc/poolc/domain/Board.java, src/main/java/poolc/poolc/repository/BoardRepository.java, src/test/java/poolc/poolc/Repository/BoardRepositoryTest.java
=> Feat. BoardRepository Create

src/main/java/poolc/poolc/Repository/MemberRepository.java
경로 수정
Close #34 
<br/>
<br/><br/>
=> Feat. ErrorModifyPath

src/main/java/poolc/poolc/domain/Project.java
=> Fix: Project column definition change char to varchar

src/main/java/poolc/poolc/domain/Member.java
=> Fix : Change column definition char to varchar

src/main/java/poolc/poolc/repository/BookRepository.java, src/test/java/poolc/poolc/Repository/BookRepositoryTest.java
=> Feat : Book delete feature add

src/main/java/poolc/poolc/domain/Project.java, src/main/java/poolc/poolc/domain/ProjectMember.java, src/main/java/poolc/poolc/repository/ProjectRepository.java, src/test/java/poolc/poolc/Repository/ProjectRepositoryTest.java
=> Feat: Project Remove feature add

src/main/java/poolc/poolc/domain/ProjectMember.java
=> Fix: Add unique constraint {member,project}

src/main/java/poolc/poolc/Repository/PostRepository.java, src/main/java/poolc/poolc/domain/Member.java, src/main/java/poolc/poolc/domain/Post.java, src/test/java/poolc/poolc/Repository/PostRepositoryTest.java
Close #32
<br/>
PostRepository에 createQuery을 작성할 때, 도메인을 통해 query문을 찾을 때, domain 객체를 가져와서 찾아야 합니다.
<br/><br/>
=> Post repository create

src/main/java/poolc/poolc/Repository/CommentRepository.java, src/main/java/poolc/poolc/Repository/PostRepository.java, src/main/java/poolc/poolc/domain/Comment.java, src/main/java/poolc/poolc/domain/Post.java, src/test/java/poolc/poolc/Repository/CommentRepositoryTest.java, src/test/java/poolc/poolc/Repository/PostRepositoryTest.java
=> Comment repository create

src/main/java/poolc/poolc/Repository/ActivityRepository.java, src/main/java/poolc/poolc/domain/Activity.java, src/test/java/poolc/poolc/Repository/ActivityRepositoryTest.java
=> Activity repository create

src/main/java/poolc/poolc/domain/Book.java, src/main/java/poolc/poolc/repository/BookRepository.java, src/main/java/poolc/poolc/service/BookService.java, src/test/java/poolc/poolc/Service/BookServiceTest.java
Close #48 
<br/>
- 책을 반납할때와 빌릴때 여러가지 예외사항을 처리하였으나 저 의외의 경우에 대한 테스트는 확실치 않음
<br/><br/>
=> Book service make

src/main/java/poolc/poolc/Repository/ActivityRepository.java, src/main/java/poolc/poolc/Repository/SessionRepository.java, src/main/java/poolc/poolc/domain/Activity.java, src/main/java/poolc/poolc/domain/Session.java, src/test/java/poolc/poolc/Repository/ActivityRepositoryTest.java, src/test/java/poolc/poolc/Repository/SessionRepositoryTest.java
=> Session repository create

src/main/java/poolc/poolc/Repository/ActivityRepository.java, src/main/java/poolc/poolc/Repository/SessionRepository.java, src/main/java/poolc/poolc/Repository/TagRepository.java, src/main/java/poolc/poolc/domain/Activity.java, src/main/java/poolc/poolc/domain/Session.java, src/main/java/poolc/poolc/domain/Tag.java, src/main/resources/application.yml, src/test/java/poolc/poolc/Repository/ActivityRepositoryTest.java, src/test/java/poolc/poolc/Repository/SessionRepositoryTest.java, src/test/java/poolc/poolc/Repository/TagRepositoryTest.java
=> Tag repository create

src/main/java/poolc/poolc/repository/BookRepository.java, src/test/java/poolc/poolc/Repository/BookRepositoryTest.java, src/test/java/poolc/poolc/Service/BookServiceTest.java
커밋을 안해서 변경사항이 안올라갔습니다.
<br/>
<br/><br/>
=> Fix: findOneWithBorrower add parameter

src/main/java/poolc/poolc/domain/Board.java, src/main/java/poolc/poolc/service/BoardService.java, src/test/java/poolc/poolc/Service/BoardServiceTest.java
=> Board service create

src/main/java/org/poolc/api/activity/repository/ActivityRepository.java, src/main/java/org/poolc/api/activity/service/ActivityService.java, src/main/java/org/poolc/api/member/configurations/MemberDataLoader.java, src/main/java/org/poolc/api/member/controller/MemberController.java, src/main/java/org/poolc/api/member/dto/MemberResponse.java, src/main/java/org/poolc/api/member/dto/RegisterMemberRequest.java, src/main/java/org/poolc/api/member/dto/UpdateMemberRequest.java, src/main/java/org/poolc/api/post/domain/Post.java, src/main/java/org/poolc/api/project/dto/ProjectResponse.java, src/main/java/org/poolc/api/project/repository/ProjectRepository.java, src/main/java/org/poolc/api/project/service/ProjectService.java, src/test/java/org/poolc/api/activity/ActivityAcceptanceTest.java, src/test/java/org/poolc/api/asciidocs/member/MemberDoc.java, src/test/java/org/poolc/api/member/MemberAcceptanceTest.java, src/test/java/org/poolc/api/project/ProjectAcceptanceTest.java
Close #82 
- 회원 가입시 introduction이 등록되지 않는 오류 수정 및 회원 정보 수정시 introduction 수정할 수 있도록 변경
- 자기 조회/ 타인 조회시 참여했던 활동(activity, project) 조인해서 볼 수 있도록 확인
- [] Merge 하는 브랜치가 올바른가?
<br/>
<br/><br/>
=> Bug fix/member api

src/main/java/org/poolc/api/auth/configurations/WebSecurityConfig.java, src/main/java/org/poolc/api/poolc/controller/PoolcController.java, src/main/java/org/poolc/api/poolc/domain/Poolc.java, src/main/java/org/poolc/api/poolc/dto/CreatePoolcRequest.java, src/main/java/org/poolc/api/poolc/dto/PoolcResponse.java, src/main/java/org/poolc/api/poolc/dto/UpdatePoolcRequest.java, src/main/java/org/poolc/api/poolc/repository/PoolcRespository.java, src/main/java/org/poolc/api/poolc/service/PoolcService.java, src/main/java/org/poolc/api/poolc/vo/PoolcCreateValues.java, src/main/java/org/poolc/api/poolc/vo/PoolcUpdateValues.java, src/test/java/org/poolc/api/poolc/PoolcAcceptanceTest.java
=> Feat: poolc api 작성

src/main/java/org/poolc/api/activity/domain/Activity.java, src/test/java/org/poolc/api/activity/ActivityAcceptanceTest.java, src/test/java/org/poolc/api/asciidocs/member/MemberDoc.java, src/test/java/org/poolc/api/book/BookAcceptanceTest.java, src/test/java/org/poolc/api/member/MemberAcceptanceTest.java, src/test/java/org/poolc/api/poolc/PoolcAcceptanceTest.java, src/test/java/org/poolc/api/project/ProjectAcceptanceTest.java
Close #
- [test] 
<br/>
- 특이 사항 1
- 특이 사항 2
<br/><br/>
=> Fix: query 문제 제외 모든 테스트 성공

src/main/java/org/poolc/api/auth/configurations/WebSecurityConfig.java, src/main/java/org/poolc/api/member/controller/MemberController.java, src/main/java/org/poolc/api/member/domain/Member.java, src/main/java/org/poolc/api/member/domain/MemberRole.java, src/main/java/org/poolc/api/member/service/MemberService.java, src/test/java/org/poolc/api/member/MemberAcceptanceTest.java, src/test/java/org/poolc/api/member/domain/MemberTest.java
- Member에 대한 단위테스트 추가
- Role이 유효한지 확인하는 validation 로직 추가
- 시그니처 통일(updateMember)
Close #
<br/>
- 특이 사항 1
- 특이 사항 2
<br/><br/>
=> refactor(Member): Member에 권한 체크 책임 부여

.envrc.ex, build.gradle, src/main/java/org/poolc/api/auth/configurations/WebSecurityConfig.java, src/main/java/org/poolc/api/member/controller/MemberController.java, src/main/java/org/poolc/api/member/domain/Member.java, src/main/java/org/poolc/api/member/dto/MemberResetRequest.java, src/main/java/org/poolc/api/member/repository/MemberRepository.java, src/main/java/org/poolc/api/member/service/MemberService.java, src/main/resources/application.yml
=> Feat: 비밀번호 초기화 메일 보내는 api 작성
